//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFresherJobs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunctionalArea
    {
        public long FunctionalAreaId { get; set; }
        public string FunctionalAreaName { get; set; }
    
        public virtual tblFresherFunctionalArea tblFresherFunctionalArea { get; set; }
    }
}
