//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFresherJobs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFresherDocument
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string ContentType { get; set; }
        public string DocumentName { get; set; }
        public int DocumentTypeId { get; set; }
        public byte[] DocumentData { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tblDocumentType tblDocumentType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
