//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFresherJobs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFresher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFresher()
        {
            this.tblFresherPreferredLocations = new HashSet<tblFresherPreferredLocation>();
            this.tblFresherFunctionalAreas = new HashSet<tblFresherFunctionalArea>();
            this.tblFresherPreferredIndustries = new HashSet<tblFresherPreferredIndustry>();
        }
    
        public long FresherId { get; set; }
        public long UserId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Counrty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool DeleteStatus { get; set; }
        public System.DateTime DOB { get; set; }
        public byte Gender { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public string ProfileSummary { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFresherPreferredLocation> tblFresherPreferredLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFresherFunctionalArea> tblFresherFunctionalAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFresherPreferredIndustry> tblFresherPreferredIndustries { get; set; }
    }
}
