//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFresherJobs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        public int id { get; set; }
        public string jobtitle { get; set; }
        public string jobsummary { get; set; }
        public string jobdescription { get; set; }
        public string publisherjobid { get; set; }
        public string city { get; set; }
        public string deeplink { get; set; }
        public string organization { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
