//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFresherJobs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreferredLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPreferredLocation()
        {
            this.tblFresherPreferredLocations = new HashSet<tblFresherPreferredLocation>();
        }
    
        public long PreferredLocationId { get; set; }
        public string PreferredLocationName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFresherPreferredLocation> tblFresherPreferredLocations { get; set; }
    }
}
